title: Saptarishi Pandey
github:
is_project_page: false
show_downloads: false
google_analytics: G-QGT94Q8KFH
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
kramdown:
  math_engine: mathjax

